module "virtual_machine" {
source = "C:/Users/Public/Documents/TerraformAzurepractice/Module"
RGname = "RG1"
location = "East US"
vnetname = "vnet1"
subnetname = "frontendsubnet"
nicname = "webvm1_nic"
ipconfig_name = "internal"
ip_allocation = "Dynamic"
vmname = "webvm1"
vm_size = "Standard_B1s"
vm_publisher = "MicrosoftWindowsServer"
vm_offer = "WindowsServer"
sku = "2016-Datacenter"
os_disk_name = "webvm1.osdisk1"
username = "Dontula"
password = "Div12456789jhgfd"
storage_type = "Standard_LRS"
}